// Flat config (ESLint 9+). `eslint-config-next` ships a CJS module whose
// `module.exports` is already a flat-config array, so the default import is that
// array and spreads directly. `/core-web-vitals` is the same set with the
// performance rules raised from warnings to errors — worth it for a UI that will
// render tables of scheduled sends.
import next from 'eslint-config-next/core-web-vitals';

// Named rather than exported anonymously — `import/no-anonymous-default-export`
// (from the Next preset) warns on a bare array literal.
const config = [
  {
    // .next holds generated output; next-env.d.ts is regenerated by next build.
    ignores: ['.next/**', 'out/**', 'next-env.d.ts'],
  },
  ...next,
  {
    rules: {
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'error',
    },
  },
];

export default config;
